global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "throttlegate"
    static_configs:
      - targets: ["gateway:9464"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
